version: '3.8'

services:
  postgres-api-france-nuage:
    container_name: postgres-api-france-nuage
    image: postgres:15
    volumes:
      - postgres_volume_france_nuage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    logging:
      options:
        max-size: '10m'
        max-file: '5'
      driver: json-file
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d avis-de-deces -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-api-france-nuage:
    container_name: redis-api-france-nuage
    image: redis:6-alpine
    volumes:
      - redis_volume_france_nuage:/data
    ports:
      - 6379:6379

#  api-france-nuage:
#    container_name: adonis_app
#    restart: always
#    depends_on:
#      - postgres
#      - redis
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - ${PORT}:${PORT}
#      - 9229:9229
#    env_file:
#      - .env
#    environment:
#      - PG_HOST=postgres
#      - REDIS_HOST=redis
#    volumes:
#      - ./:/home/node/app
#    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

volumes:
  postgres_volume_france_nuage:
  redis_volume_france_nuage:
